"""empty message

Revision ID: 09e2f4df1e23
Revises: f8cf896a5634
Create Date: 2021-09-08 02:01:08.804261

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '09e2f4df1e23'
down_revision = 'f8cf896a5634'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appointments', sa.Column('duration', sa.Integer(), nullable=True))
    op.add_column('appointments', sa.Column('confirmation', sa.Boolean(), nullable=True))
    op.add_column('student', sa.Column('email', sa.String(), nullable=True))
    op.add_column('student', sa.Column('age', sa.Integer(), nullable=True))
    op.add_column('student', sa.Column('grade', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('student', 'grade')
    op.drop_column('student', 'age')
    op.drop_column('student', 'email')
    op.drop_column('appointments', 'confirmation')
    op.drop_column('appointments', 'duration')
    # ### end Alembic commands ###
