"""empty message

Revision ID: 3c61b72588a5
Revises: dc40343dc782
Create Date: 2021-09-08 00:52:04.212383

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '3c61b72588a5'
down_revision = 'dc40343dc782'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tutor', 'availableTime')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tutor', sa.Column('availableTime', postgresql.ARRAY(postgresql.TIMESTAMP()), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
