"""empty message

Revision ID: 7254e0ee3f44
Revises: 833c15d609de
Create Date: 2021-09-08 04:55:22.543689

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7254e0ee3f44'
down_revision = '833c15d609de'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('appointments', 'confirmation',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('appointments', 'confirmation',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###
