"""empty message

Revision ID: 776fd3e49777
Revises: 3c61b72588a5
Create Date: 2021-09-08 00:52:18.627553

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '776fd3e49777'
down_revision = '3c61b72588a5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tutor', sa.Column('availableTime', sa.ARRAY(sa.String()), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tutor', 'availableTime')
    # ### end Alembic commands ###
