"""empty message

Revision ID: 833c15d609de
Revises: 09e2f4df1e23
Create Date: 2021-09-08 04:03:10.783758

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '833c15d609de'
down_revision = '09e2f4df1e23'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('appointments', 'confirmation',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('appointments', 'confirmation',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###
