"""empty message

Revision ID: 83353ab16c4f
Revises: 
Create Date: 2021-09-06 23:40:34.844415

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '83353ab16c4f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Student',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Subject',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Tutor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('intro', sa.String(), nullable=True),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['subject_id'], ['Subject.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Appointments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('tutor_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['Student.id'], ),
    sa.ForeignKeyConstraint(['tutor_id'], ['Tutor.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Appointments')
    op.drop_table('Tutor')
    op.drop_table('Subject')
    op.drop_table('Student')
    # ### end Alembic commands ###
