"""empty message

Revision ID: dc40343dc782
Revises: 6149ef7820b0
Create Date: 2021-09-08 00:09:38.799867

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dc40343dc782'
down_revision = '6149ef7820b0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('student',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('appointments', sa.Column('start_time', sa.DateTime(), nullable=False))
    op.add_column('appointments', sa.Column('student_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'appointments', 'student', ['student_id'], ['id'])
    op.alter_column('subject', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.add_column('tutor', sa.Column('availableTime', sa.ARRAY(sa.String()), nullable=True))
    op.alter_column('tutor', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('tutor', 'intro',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tutor', 'intro',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('tutor', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('tutor', 'availableTime')
    op.alter_column('subject', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_constraint(None, 'appointments', type_='foreignkey')
    op.drop_column('appointments', 'student_id')
    op.drop_column('appointments', 'start_time')
    op.drop_table('student')
    # ### end Alembic commands ###
